name: Doctest
inputs:
  working_directory:
    required: true
    description: Directory containing the Makefile
runs:
  using: composite
  steps:
    - name: Run doctests
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -exuo pipefail

        cd docs
        make clean
        make html
        make doctest
