package:
  name: yahp
  version: "0.0.14"

source:
  git_url: https://github.com/mosaicml/yahp.git
  # TODO should be v0.0.14
  git_rev: ravi/conda
  git_depth: 1

channels:
  - defaults
  - conda-forge

build:
  number: 0

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7
    - pyyaml >=5.4.1
    - ruamel.yaml >=0.17.10

test:
  requires:
    - pytest >=7.0.0
    - pytest-timeout >=1.4.2
    - toml >=0.10.2
    
  imports:
    - yahp
  commands:
    - pytest

about:
  home: https://github.com/mosaicml/yahp
  license: Apache 2.0
  license_file: LICENSE
  doc_url: https://docs.mosaicml.com/projects/yahp/en/stable/
