# Anaconda configuration for yahp

package:
  name: yahp
  version: "{{ load_setup_py_data().get('version') }}"

source:
  git_url: ./

channels:
  - defaults
  - conda-forge

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.7
    - setuptools
    - git
  build:
    - git
  run:
    - python >=3.7
    - pyyaml >=6.0,<7
    - docstring_parser ==0.13
    - ruamel.yaml >=0.17.10,<0.18
    - jsonschema >=4.7.2,<4.8

test:
  requires:
    - pytest >=7.1.0,<8
    - pytest-timeout >=1.4.2
    - toml >=0.10.2,<0.11
  files:
    - "**/yahp/**"
    - "**/tests/**"
    - "**/pyproject.toml"
  imports:
    - yahp
    - tests
  commands:
    - pytest

about:
  home: https://www.mosaicml.com
  license: Apache 2.0
  license_file: LICENSE
  summary: "Yet Another HyperParameter Framework"
  dev_url: https://github.com/mosaicml/yahp
  doc_url: https://docs.mosaicml.com/projects/yahp/en/stable/
